



:: # Find Music (in Peter-Tagged Markdown Files)
:: 
:: ## About
:: - 2021-05-09T14:46:00-05:00
:: - mangelsdorf-peter-james.1999-02-11.201943
:: - find all music I want to listen to
:: - see projects/daily/2021-05-09/misc.md for more details
:: 
:: ## Future
:: - Use Python instead
:: - Include source file and line for each found section
:: - Ignore files with tag "autogen"
:: - Use a proper markdown processor




@echo off
title Don't echo this stuff




title Set Variables
:: Allow easier way of referencing from file
set findmus-date=%date%
set findmus-time=%time%
set findmus-author=mangelsdorf-peter-james.1999-02-11.201943
set nam-mus-fil=findmus.%findmus-date%.temp.nam-mus-fil.md
set tag-mus-fil=findmus.%findmus-date%.temp.tag-mus-fil.md
set tag-mus-sec=findmus.%findmus-date%.temp.tag-mus-sec.md
set fin-raw-lines=findmus.%findmus-date%.temp.fin-raw-lines.md
set fin-raw-blanks=findmus.%findmus-date%.temp.fin-raw-blanks.md
set fin=findmus.%findmus-date%.final.md




title Delete Existing Files
:: Prevent searching in old files
if exist %nam-mus-fil%    ( del %nam-mus-fil% )
if exist %tag-mus-fil%    ( del %tag-mus-fil% )
if exist %tag-mus-sec%    ( del %tag-mus-sec% )
if exist %fin-raw-lines%  ( del %fin-raw-lines% )
if exist %fin-raw-blanks% ( del %fin-raw-blanks% )
if exist %fin%            ( del %fin% )




title Get Names of all markdown files with "music" in their name
ag -g music*.md >> %nam-mus-fil%




title Names of all markdown files with "music" as a tag in their bodies
ag -l -G .md "\n- music" >> %tag-mus-fil%




title All extracted markdown sections with "music" as a tag
for /F "tokens=*" %%A in (%tag-mus-fil%) do (
  ag --nonumbers -B 4 -A 4 "\n- music" %%A >> %tag-mus-sec%
)




title All extracted markdown sections with "music" and "later" as tags but lines
for /F "tokens=*" %%A in (%nam-mus-fil%) do (
  ag --nonumbers -B 4 "\n- later" %%A >> %fin-raw-lines%
)
ag --nonumbers -B 4 "\n- later" %tag-mus-sec% >> %fin-raw-lines%




title All extracted markdown sections with "music" and "later" as tags but blanks
findstr /V \-\- %fin-raw-lines% >> %fin-raw-blanks%




title Final Cleaned-up Results
:: Include a Header
echo. >> %fin%
echo. >> %fin%
echo # Music To Listen To >> %fin%
echo. >> %fin%
echo. >> %fin%
echo ## About >> %fin%
echo - Created %findmus-date%T%findmus-time% >> %fin%
echo - Creator %findmus-author% >> %fin%
echo - Find all music I want to listen to in Peter-Tagged Markdown Files >> %fin%
echo - Generated by `findmus.bat` v1.0 >> %fin%
echo - NOTRACK >> %fin%
echo - AUTOGEN >> %fin%
echo - Do Not Edit >> %fin%
echo - Machine Generated >> %fin%
echo - Unspecified >> %fin%
echo - Ad Hoc >> %fin%
echo. >> %fin%
echo. >> %fin%
echo. >> %fin%
echo. >> %fin%
:: Add Content without garbage lines or blank-lines
findstr /V "^$" %fin-raw-blanks% >> %fin%




title Delete Intermediary Files
del %nam-mus-fil%
del %tag-mus-fil%
del %tag-mus-sec%
del %fin-raw-lines%
del %fin-raw-blanks%




title Release Variables
set findmus-date=
set findmus-time=
set findmus-author=
set nam-mus-fil=
set tag-mus-fil=
set tag-mus-sec=
set fin-raw-lines=
set fin-raw-blanks=




title Resume Echoing
@echo on




title OPTIONAL Open Final File
code %fin%
set fin=




title Done




:: ## Misc
:: 
:: ### Tags
:: - ag
:: - silver searcher
:: - file search
:: - text search
:: - search
:: - escape character
:: - escapes
:: - ag case
:: - ag sensitive
:: - help
:: - technical
:: - advice
:: - tutorial
:: - batch
:: - windows
:: - win10
:: - cmd
:: - prompt
:: - script
:: - cli
:: - commandline
:: - command line interface
:: - text interface
:: - terminal
:: - dos
:: - file
:: - fileoperation
:: - textfile
:: 
:: ### Notes
:: - ag has some very unhelpful debug messages
:: - apparently single-quotes do not work on Windows
:: - Need to use Double-Quotes
:: - ag has really awful escaping rules
::   - if `-` is the first character in a sequence, it needs to be escaped like `\-`
:: - ag does not use the regex slashes (`/..../`) to declare a regex pattern
::   - instead ag uses double-quotes, and does a poor job of containing strings within them
:: - Use `echo string > filename` to overwrite (Windows)
:: - Use `echo string >> filename` to append (Windows)
:: - ag's `--before` does not work on Windows, use `-B` instead
:: - use `-B` (before) and `-A` (after) to see lines nearby a tag
:: - use `echo %date%` for date
:: 
:: ### References
:: - [How do you search for a “$” using ag (silver-searcher)?](https://superuser.com/questions/1105372/how-do-you-search-for-a-using-ag-silver-searcher/1105381)
:: - [How can I search for a multiline pattern in a file?](https://stackoverflow.com/questions/152708/how-can-i-search-for-a-multiline-pattern-in-a-file)
:: - [ag Silver Searcher: rules for lookahead/lookbehind patterns?](https://stackoverflow.com/questions/22190334/ag-silver-searcher-rules-for-lookahead-lookbehind-patterns)
:: - [What is the regex to match a newline character?](https://emacs.stackexchange.com/questions/9548/what-is-the-regex-to-match-a-newline-character)
:: - [Ack/Ag/Pt just list files?](https://superuser.com/questions/1253487/ack-ag-pt-just-list-files)
:: - [Append text with .bat](https://stackoverflow.com/questions/5139157/append-text-with-bat/5143293)
:: - [How do you loop through each line in a text file using a windows batch file?](https://stackoverflow.com/questions/155932/how-do-you-loop-through-each-line-in-a-text-file-using-a-windows-batch-file)
:: - [What does “@” mean in Windows batch scripts](https://stackoverflow.com/questions/8486042/what-does-mean-in-windows-batch-scripts)
:: - [grep a file, but show several surrounding lines?](https://stackoverflow.com/questions/9081/grep-a-file-but-show-several-surrounding-lines)
:: - [Delete certain lines in a txt file via a batch file](https://stackoverflow.com/questions/418916/delete-certain-lines-in-a-txt-file-via-a-batch-file)
:: - [grep a file, but show several surrounding lines?](https://stackoverflow.com/questions/9081/grep-a-file-but-show-several-surrounding-lines)
:: - [How to get date in BAT file](https://stackoverflow.com/questions/19131029/how-to-get-date-in-bat-file)
:: - [Batch Script - Variables](https://www.tutorialspoint.com/batch_script/batch_script_variables.htm)
:: - [How to verify if a file exists in a batch file?](https://stackoverflow.com/questions/3022176/how-to-verify-if-a-file-exists-in-a-batch-file#3022193)
:: - [List all environment variables from the command line](https://stackoverflow.com/questions/5327495/list-all-environment-variables-from-the-command-line)
:: - [FOR/DO command gives “Was unexpected at this time” when run from command prompt](https://superuser.com/questions/894475/for-do-command-gives-was-unexpected-at-this-time-when-run-from-command-prompt)
:: - [Command line to remove an environment variable from the OS level configuration](https://stackoverflow.com/questions/13222724/command-line-to-remove-an-environment-variable-from-the-os-level-configuration)
:: - [In batch, how do I create spaces at the beginning of a input prompt string?](https://stackoverflow.com/questions/9864620/in-batch-how-do-i-create-spaces-at-the-beginning-of-a-input-prompt-string)


